const events = module.exports = {};

events.SEND_QUESTION = 'SEND_QUESTION';
events.RECEIVE_QUESTION = 'RECEIVE_QUESTION';
events.SEND_ANSWER = 'SEND_ANSWER';
events.RECEIVE_ANSWER = 'RECEIVE_ANSWER';
events.CREATE_ROOM = 'CREATE_ROOM';
